### ISSUE TITLE
Position offset of "Springboard" Text on top of launcher

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#10]
The displayed text "Springboard" and other text has an offset to the bottom when the launcher is opened. This happens sometimes and I didn't find a way to safely reproduce it.

Screenshot
![Screenshot_20200902-070038.png](https://user-images.githubusercontent.com/67801045/91934091-b1571c80-ecea-11ea-9c50-dc70e1f79689.png)

**Comment by wurzer** [comment]
Should be solved with the current release
