### ISSUE TITLE
Springboard tabs don't get cleared

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#11]
If I olen the "Threads" tab via the red dot and select one message there the message gets opened in a new tab. If I swipe right two times I'm back on the launcher main page.
When I now select "News" via the red dot the tab opens. Swiping left now shows the previous message tab which didn't get cleared.

[Video](https://mynextcloudpi.feste-ip.net/index.php/s/LQdArfqzrHeMrFQ)

**Comment by wurzer** [comment]
Could you recheck it after the weekend? I assume it was an error in the background, when the threading didn't work.

**Comment by wurzer** [comment]
I can’t reproduce this behavior. I’m confused regarding the first step: Do you open „threads“ and tap on one of the threads afterwards?

**Comment by SHA-NDY** [comment]
Yes, I do it like that

**Comment by wurzer** [comment]
I  can’t reproduce it. I assume a further condition for this case. Did you update to release 1.0.32? I assume a not visible exception in the background. Can you reproduce this behavior for each thread and also for contacts?

**Comment by SHA-NDY** [comment]
I updated to Version 1.0.32. It is the same with contacts and threads.

**Comment by wurzer** [comment]
I think you mean:
> When I now select "News" via the red dot the tab opens. Swiping **right** now shows the previous message tab which didn't get cleared.

Will be fixed with next version > 1.0.32

**Comment by SHA-NDY** [comment]
Issue still present in 1.0.34

**Comment by SHA-NDY** [comment]
Still present in 1.0.36

**Comment by wurzer** [comment]
Should be fixed in release > 1.1.0

**Comment by SHA-NDY** [comment]
Fixed!
