### ISSUE TITLE
Typo when adding to shortcuts again

### ISSUE THREAD

**Issue by confestim** [HelloVolla/android-launcher-qt#114]
There is a typo when adding an app that is already in shortcuts. The little dialogue box reads: "You have alresdy added the shortcut". 

![Typo](https://cdn.discordapp.com/attachments/1000065977226108939/1066670068131442708/Screenshot_20230122-114454_Volla.png)

**Comment by wurzer** [comment]
Is fixed in release2.1.7, currently beta
