### ISSUE TITLE
Crash when using Gesture Navigation

### ISSUE THREAD

**Issue by anick3** [HelloVolla/android-launcher-qt#119]
Settings -> System -> Advanced -> Gestures -> System navigation -> Gesture navigation (activate),

Close all apps, open some, close them, and Volla launcher will inevitably crash.

Volla Phone 22, latest Volla OS release with all updates

**Comment by wurzer** [comment]
I can't confirm any crash. It's properly working with Volla OS 11.1 (11.01.2023) and Volla Launcher 2.1.12 (beta).
