### ISSUE TITLE
Alignment and typo in peoples list

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#12]
When I pick someone from the people category the calls with this person are listed. There is a typo in one line (parsing issue?).
And how is the alignment done? Looks a little random (right and left alignment).

![Screenshot_20200909-195942.png](https://user-images.githubusercontent.com/67801045/92636312-6daa7700-f2d7-11ea-9cb9-50657ce3ed95.png)

**Comment by SHA-NDY** [comment]
Ah ok, it's not a typo. The text is outside the display area because this line is aligned to the right side of the screen.

**Comment by wurzer** [comment]
I assume, that something is wrong with the text field, because you find the correct week day in other entries. I'll take a look.

**Comment by SHA-NDY** [comment]
I think it's too much text for one line

**Comment by wurzer** [comment]
Will be fixed in next release > 1.1.0

**Comment by wurzer** [comment]
Solved in recent release by abbreviated weekdays
