### ISSUE TITLE
Small typo in reset options

### ISSUE THREAD

**Issue by js-xc** [HelloVolla/android-launcher-qt#125]
https://github.com/HelloVolla/android-launcher-qt/blob/831fd5f14ea7f9b0002c6ef05fe43b0c959e02d3/translations/Volla_de.ts#L490

"Kurzbefehele" --> "Kurzbefehle"

(I am aware it took me longer to write this issue than it would have to just fix it myself but I was not sure whether this kind of contribution was welcome and how it should be done.)

**Comment by wurzer** [comment]
Thanks! will be fixed with next release.
