### ISSUE TITLE
Launcher crashes and refuse to start even after reboot

### ISSUE THREAD

**Issue by rtng** [HelloVolla/android-launcher-qt#131]
Volla Launcher Version 2.1.14
Volla Phone 22
VollaOS 11.1-2023111-Stable-mimameid

had already experienced some minor vulnerabilities, such as starting problems after deleting notes created with this launcher and similar.
But now the launcher doesn't start at all, even after a system reboot. It can also no longer be started directly from the screen. The note that the app does not start and the option to exit the app only appear briefly and then disappear before you can click on the option.
After that, the display is actually completely useless and luckily you can just reach the settings button in the status bar to switch to the saving Trebuchet app.
It would be important if this bug is fixed in a timely manner.
The Volla Launcher makes sense, is actually very practical and I would hate to be without it. But I can't call it stable at all.

The cause may be found in the cooperation with some system settings and the Volla launcher.
Just before the crash I tried to change the background for the start screen and the lock screen...
but that's just a vague guess!

**Comment by wurzer** [comment]
Please update to version 2.1.19 and remove app data

**Comment by rtng** [comment]
Ah OK, remove app-data path?

**Comment by rtng** [comment]
Hello, you closed this very quickly.
I don't see any way here in the volla phone to update the launcher and could not find a way to do so in the guide.
So could you please discribe how to fulfill what you suggested?
Thanks

Am 29. März 2023 13:51:37 MESZ schrieb "Dr. Jörg Wurzer" ***@***.***>:

**Comment by wurzer** [comment]
The launcher can be updates with F-Droid:

1. Open F-Droid
2. Swipe down to update the package information of available software.
3. If the package information is updated, tap on the clock symbol for open tasks
4. Tap on the entry for the Volla app to update the launcher

To reset the launcher, you can do the following steps:

1. Open system settings
2. Open Apps & Notifications
3. Open the list of all apps
4. Scroll down to the Volla app
5. Tap on this entry and force the app to close
6. Typ on he entry for app data an remove the app data

**Comment by rtng** [comment]
Well, the first 1 to 4 steps i already tried before . after swiping down to update i got an errormessage sth like "Volla Repository: no files found for https://fdroid/volla.tech/fdroid/ All other packges did'nt prompt any error. "
So there seems to be somthing wrong with the source (probably the URL?) i don' t know.. The matter steps i can't try without that's been solved.

Am 29. März 2023 16:29:50 MESZ schrieb "Dr. Jörg Wurzer" ***@***.***>:

**Comment by rtng** [comment]
actually the latter steps i could and i did.
the result is that volla-launcher is running again and the lock -screen is black again what i prefer over not having the launcher.
But to update the launcher is still not possible as described above.

**Comment by rtng** [comment]
finally! one needs to check the "Volla Nightly Repository" under the f-droid settings too.
Here it was still unchecked as 'by default' . Now Volla Launcher has been updated to Version 2.1.19 as you suggested.
Thank you so far and 
keep it up !:)

**Comment by wurzer** [comment]
>  But to update the launcher is still not possible as described above.

Please activate the transparent mode in the launcher. The dark mode automatically configures a black background for the lock screen.

> Well, the first 1 to 4 steps i already tried before . after swiping down to update i got an error message sth like "Volla Repository: no files found for https://fdroid/volla.tech/fdroid/ All other packages didn't prompt any error. "

The repository link is broken. If you have Telegram you can write a private message to m_aurel, so I can reply with a repository link. 

> btw one or two last suggestions from here, it would be great to be able to open files and apps with that springboard

Good idea. Thanks. We are also working to enable plugins for the skills of the launcher, because many people have such great ideas.
