### ISSUE TITLE
RSS feed title in settings misaligned

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#14]
Alignment problem with the title of the RSS feed
 http://rss.focus.de/fol/XML/rss_folnews.xml

The text is also expanded to the apps tab.

![Screenshot_20200918-123951.png](https://user-images.githubusercontent.com/67801045/93589019-863c2080-f9ac-11ea-9db0-8cc03abccee6.png)

![Screenshot_20200918-124002.png](https://user-images.githubusercontent.com/67801045/93589028-89cfa780-f9ac-11ea-959c-fda69c7afc8b.png)

**Comment by SHA-NDY** [comment]
The misalignment is also present in Nextcloud news, so it's related to the feed itself.

![Screenshot_20200918-195834.png](https://user-images.githubusercontent.com/67801045/93630196-df767500-f9e9-11ea-9bdf-5e8d9a1e7647.png)

**Comment by wurzer** [comment]
In the next update the names will be trimmed. Thanks for the example

**Comment by wurzer** [comment]
The app truncates the title now
