### ISSUE TITLE
Specific RSS feeds not working

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#15]
The following feeds generate an error message when added (works on nextcloud news app):

https://www.computerbase.de/rss/news.xml

![Screenshot_20200918-124604.png](https://user-images.githubusercontent.com/67801045/93589363-02366880-f9ad-11ea-9fc5-2fb9ef7199c5.png)

https://www.heise.de/newsticker/heise-atom.xml

![Screenshot_20200918-124726.png](https://user-images.githubusercontent.com/67801045/93589479-25611800-f9ad-11ea-8903-5cce65eab912.png)

**Comment by wurzer** [comment]
Only RSS feeds are currently supported, not Atom feeds.
