### ISSUE TITLE
display daily schedule on springboard home screen

### ISSUE THREAD

**Issue by veragn** [HelloVolla/android-launcher-qt#150]
I would love to see some kind of simple Calendar plugin for the springboard, where one could see an overview of today's planned events. 
This way one wouldn't need to open the calendar app just to see what's up next

**Comment by wurzer** [comment]
As a so called collection? Good idea. I mark this ticket as an improvement proposal

**Comment by Lucas-Sichardt** [comment]
Hi, 

I would appreciate this too.
It would also be nice to select the calendars to be taken in account for this.

In addtition it would be nice to have a second section for notes with support for todo.txt format as this is a very good and simple file format for notes for which you have several GUI software choices on every operating system (I use Sleek at desktop systems privately and at work as well as "Simpletask" in combination with NExtcloud.).

**Comment by wurzer** [comment]
See #153 

You can share notes with other apps using the sharing buttin.
