### ISSUE TITLE
Wrong contact name in conversation

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#16]
The conversations tab shows a contact name (here "Boris Thurau") instead of the phone number of the sender (here Paypal which is not a contact)

![Screenshot_20200921-200258.png](https://user-images.githubusercontent.com/67801045/93804004-f1ecea80-fc45-11ea-9df8-38906f299ad2.png)

**Comment by SHA-NDY** [comment]
Still there in 1.0.36

**Comment by wurzer** [comment]
Can you tell me the length of both numbers or an anonymized version that is syntactically equivalent? I will add another constraint for the match in the next update.

**Comment by SHA-NDY** [comment]
The PayPal number is 72972. These numbers are contained in my contacts' home number +4997359268972

**Comment by SHA-NDY** [comment]
Seems to be fixed in 1.1.4
