### ISSUE TITLE
Tap on News Settings creates multiple entries

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#17]
In the news section in the settings tab the existent news entries are getting duplicated by each tap on the heading "Nachrichtenkanäle".

[Video](https://mynextcloudpi.feste-ip.net/index.php/s/3HtaG8irPynYjS6)

This happened after I removed some of my manually added feeds.

When I remove all duplicate entries the behaviour can't be reproduced.

**Comment by wurzer** [comment]
Should be fixed in the recent versions
