### ISSUE TITLE
editing notes in volla launcher broken badly

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/android-launcher-qt#171]
When creating a new note the text editor seems to work fine.
But opening an existing note and trying to position the cursor inside the text for further editing, it happens often that parts of the text get erased. As there is no "undo" functionality there is no way to get the text back.
At least once out of 10 attempts to edit the text end up with erased lines.

**Comment by franco-bez** [comment]
Am I the only one experiencing this problem ?
To me this renders the note taking functionality in volla launcher completely useless.
Hard to imagine that no one else is affected.

In the german language forum I was told that this bug is known, but as I could not find a matching bug report I decided to create one myself.
[https://forum.volla.online/viewtopic.php?p=3141#p3141](url)

**Comment by wurzer** [comment]
I will have a look at it. Please make sure, that you use the  recent release 2.2.15

**Comment by franco-bez** [comment]
Yes the latest release 2.2.15 is installed.
The problem most often occurs when you tap in the caption line, the first Line with the bigger font, then inside the text, then back to the caption.

I took a small video. in this video it was the very first tap in the caption line that ruined the note.

https://github.com/HelloVolla/android-launcher-qt/assets/4195055/6f34d6f0-998d-43bf-9202-f45954ab688c

**Comment by wurzer** [comment]
I'll check it

**Comment by wurzer** [comment]
Should be fixed now with 2.2.17
