### ISSUE TITLE
Belgium app list for new icons

### ISSUE THREAD

**Issue by ruditimmermans** [HelloVolla/android-launcher-qt#172]
Hi,

Here would be the list of the Belgium most used apps.

Itsme
Payconiq By Bancontact
My Bpost
Argenta
Beeper
TikTok
Facebook Lite
De Lijn
Doccle
Bitwarden
Engie SMART
Proximus+ edit: The app names changed on 28/09/2023 from MyProximus to Proximus+
Money Lover
Norton 360
Woolsocks
mynexuzhealth
And soon MailFence but this app would be still Aplha what i'm testing we need to make an icon later for that.

Thanks!

**Comment by wurzer** [comment]
In progress

**Comment by wurzer** [comment]
@ruditimmermans You the Belgium's app icons in the dev branch. You are welcome to extend the mapping in the `AppGrid.qml` file.

**Comment by ruditimmermans** [comment]
OK thanks i do that right away ;)
