### ISSUE TITLE
We need to add a few more icons for Belgium apps

### ISSUE THREAD

**Issue by ruditimmermans** [HelloVolla/android-launcher-qt#174]
Here are the names and links to the play store

1. Easy Banking App - https://play.google.com/store/apps/details?id=com.bnpp.easybanking

2. Belfius Mobile - https://play.google.com/store/apps/details?id=be.belfius.directmobile.android

3. Lidl PLus - https://play.google.com/store/apps/details?id=com.lidl.eci.lidlplus

4. Xtra - https://play.google.com/store/apps/details?id=be.colruyt.xtra

5. Messenger - https://play.google.com/store/apps/details?id=com.facebook.orca

6. Safeoneweb - https://play.google.com/store/apps/details?id=be.ccb.safeonweb

7. 2dehands - https://play.google.com/store/apps/details?id=be.tweedehands.m

8. Glimp notifications - https://play.google.com/store/apps/details?id=de.nullgrad.glimpse

9. OpenCalc - https://f-droid.org/en/packages/com.darkempire78.opencalculator/

10. AfterShock - https://play.google.com/store/apps/details/AfterShock?id=com.asvcorp.aftershock

11. Helena - https://play.google.com/store/apps/details?id=care.helena.patient

**Comment by ruditimmermans** [comment]
@wurzer

**Comment by wurzer** [comment]
Apps are automatically turned into a b/w color to be aligned to the overall design concept. Whoch apps are really essential for the market in Belgium?

**Comment by ruditimmermans** [comment]
The most apps i see on overal smartphones here and know the be used daily, becoss i see many people and we have now a new Volla Phone user in Belgium mebay you know from Patricia are this apps:

Easy Banking App - https://play.google.com/store/apps/details?id=com.bnpp.easybanking

Belfius Mobile - https://play.google.com/store/apps/details?id=be.belfius.directmobile.android

Lidl PLus - https://play.google.com/store/apps/details?id=com.lidl.eci.lidlplus

Xtra - https://play.google.com/store/apps/details?id=be.colruyt.xtra

Messenger - https://play.google.com/store/apps/details?id=com.facebook.orca

Safeoneweb - https://play.google.com/store/apps/details?id=be.ccb.safeonweb

2dehands - https://play.google.com/store/apps/details?id=be.tweedehands.m

Glimp notifications - https://play.google.com/store/apps/details?id=de.nullgrad.glimpse

Helena - https://play.google.com/store/apps/details?id=care.helena.patient

**Comment by ruditimmermans** [comment]
We have for example more then 5 bank apps and everyone use a difrent bank but the ones we have on the above list are most used, the rest of the apps are utilities like Safeoneweb is a federal app that warn people phising stuff the other apps like Xtra and Lidl Plus are apps for food stores and Helena for example are for medicens .... But users here use a lot of apps here when i see people smartphones every week, and the new Volla users use all the above apps
