### ISSUE TITLE
New bug when editing notes - blank lines not handled well

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/android-launcher-qt#183]
I updated to Volla 2.2.17 as this Version fixes the bug that killes random lines when editing notes. #171 

now, this Version introduced a new bug in notes editing.

Try to enter a note that has a blank line for better readability breaks text editing.

Sample - what I try to enter:
Testnote
Testline1

Testline3

What gets entered:
Testnote
Testline1
3
e
n
i
l
t
s
e
T

---------------------------
really strange

**Comment by wurzer** [comment]
I can confirm. Will look at it

**Comment by franco-bez** [comment]
I just installed Version 2.2.18 of Vollalauncher
Handling of the "Enter" key is becoming stranger
Now there is no way at all to enter a blank line.
I took a short video you can see which keys are entered on the keyboard

file:///data_ssd2/franco/Volla/screen-20231030-111155.mp4

**Comment by franco-bez** [comment]
Just updated to Version 2.2.19

same problem as with Version 2.2.18

**Comment by wurzer** [comment]
I can't reproduce the issue any more. Please provide the steps, how to reproduce the reported issue.

**Comment by franco-bez** [comment]
just watch the video.
in words.
take a new note
title aaaaa then Enter Key
first line bbbbbb
then use the Enter key several times
Expected result
blank lines following the bbbbbb line

Result is that cursor jumps in the first line on 2 nd Enter key press
the next time enter is pressed a line break gets inserted in th title right after the first letter and so on

30.10.2023 18:33:19 Dr. Jörg Wurzer ***@***.***>:

**Comment by franco-bez** [comment]
today I installed Version 2.2.20

Now blank lines can be entered.

But everytime the note is closed and reopend ( i.e. swipe left to notes overview, then tap on the note with blank lines) the blank lines get doubled. 
Really strange.

**Comment by wurzer** [comment]
I'll check it. If you are a developer, you may have a look at the parsing function from line 2020 https://github.com/HelloVolla/android-launcher-qt/blob/master/Details.qml

**Comment by franco-bez** [comment]
I see that there is some transformation being done with html tags.
I do not really understand why this is done at all.
I wonder what would happen if the lines 213 up to 233 would be removed ?
Is there any transformation being done in "mainView.updateNote" ?

![Screenshot_20231106-173205_Volla](https://github.com/HelloVolla/android-launcher-qt/assets/4195055/7e89802f-5ab0-489e-8430-1d35dcd67ba0)

after I entered the note above I get notes.json
![Auswahl_670](https://github.com/HelloVolla/android-launcher-qt/assets/4195055/1d5c7b72-1e80-4f06-9ef9-ddf1150d17b2)
the new line has the hex codes E2 80 A9

after swiping back to the overview and then taping on the note again without entering any key I get
![Auswahl_671](https://github.com/HelloVolla/android-launcher-qt/assets/4195055/e2f0bed4-bfe6-4a27-a1dd-69ecf43b07d5)
now the new line has E2 80 A9 E2 80 8B E2 80 A9

**Comment by franco-bez** [comment]
Do we need / want this markup stuff in the simple notes?
Myself I would not have expected any of this to happen.
I expected just a simple plain text editor with no magic at all.

**Comment by franco-bez** [comment]
yesterday I updated to version 2.3.0.
The situation is unchanged.

I understand that having the support for markup language would be a fine feature.
But in my humble opinion this is only useful if it works flawlessly.
So either one should invest a lot of testing and debugging to make it work, or drop the feature for now and have a working note taking without markup support.

**Comment by wurzer** [comment]
Yes, the beta doesn't contain another modification for editing behaviour. But it should be possible no to add a new line in a note.

**Comment by franco-bez** [comment]
yes, a new line can be entered.
But every new line gets doubled every time a note is viewed, although no edits are done.
I already tried to describe this a little up the thread.

I try again:
1. Create a new note with a blank line.
2. return to the notes overview page.
3. tap on the note to view/edit it.
now there are two blank lines.
4. once again return to the notes overview page.
5. tap the note again.
now there are four blank lines.

and so on, in every cicle the ammount of new lines doubles.

**Comment by StaffanMelin** [comment]
I can confirm that this issue is still there, blank lines are doubled. Makes the Notes function, which is great, really problematic. Please fix! :)

**Comment by k-kirill** [comment]
I do suggest you disable the notes feature until you make it work without spoiling user notes, otherwise it really makes a very bad impression on new users.

**Comment by franco-bez** [comment]
just updated to 2.4.7.
now notetaking is broken completely.
No text input possible as there is no Keyboard displayed.

**Comment by franco-bez** [comment]
just updated to 2.4.8.

still completely broken.

When I try to add a note there is no keyboard, so there is no way to enter text at all

**Comment by franco-bez** [comment]
sorry for the confusion.
I found out that there is only a very narrow area on screen where I have to tap in order to enter the edit mode and bring up the keyboard.

the problem with blank lines is still the same.

**Comment by wurzer** [comment]
I can conform, that empty lines are added. Will into it.

**Comment by franco-bez** [comment]
Version 2.4.14 seems to have fixed this issue.
Good Job
