### ISSUE TITLE
[2.2.20] "Use colored app icons" setting not persistant

### ISSUE THREAD

**Issue by je-nix** [HelloVolla/android-launcher-qt#197]
Hi there

I'm having the issue that my volla launcher does not persist the "Use colored app icons" option in version 2.2.20. When enabling it, the app icons switch from black and white to colored. After some interactions (opening an app, turning off the screen) the option gets disabled again and they switch back to black and white.
Other options are persistent. I can't tell if this issue was introduced with 2.2.20 as I only tested it with this release.

Please let me know if I can assist  in providing more info or testing.

Thanks already.

**Comment by wurzer** [comment]
Hello, I tested this behaviour from this morning and can't confirm. Please try to reset the app to make sure, that there is not conflict with the data storage of the app. If there is a conflict, thatn the setting moght not be stored that the dafailt setting is used after a restart of the app.

**Comment by je-nix** [comment]
Thanks for getting back to me.
Resetting the app (using the "Reset launcher" entry in the "Reset options" on the launcher settings) worked, the issue has now disappeared.
Marking the issue as closed, thank you so much for the support.
