### ISSUE TITLE
Add notification dot support for apps like K-9 Mail, WhatsApp, Telegram, etc

### ISSUE THREAD

**Issue by k-kirill** [HelloVolla/android-launcher-qt#200]
I have the "Allow notification dot" setting enabled for K-9 Mai,l WhatsApp, Telegram, etc. and while the Trebuchet launcher shows notifications dots when there are corresponding notifications for the apps, the Volla launcher does not show them. It would be nice if the Volla launcher supported them as in addition to calls and SMS/MMS that have notification red dots a lot of communication is happening via email and other messengers. Thanks!

**Comment by franco-bez** [comment]
The "problem" also works the other way around.
When you dismiss a notification by pulling it down from the top and swiping it away trebuchet removes the dot from the application as no notification is active.

Volla on the other hand insists that the app is launched from volla launcher, otherwise the dot remains.

**Comment by k-kirill** [comment]
I am using Volla Launcher 2.4.10 and notifications dots are displayed regardless of the "Allow notification dot" permission for specific apps and regardless of the notifications being read or not. I wish it were implemented like in the Trebuchet launcher that respects the permission and shows the dot only for unread notifications.

**Comment by wurzer** [comment]
The expected - and only technical possible - behaviour is, that the the notification dot is removed, if the app os opened from the launcher.

**Comment by franco-bez** [comment]
I doubt that the only technically possible behaviour to get the notification dot removed is that the app gets launched from the launcher.

Trebuchet and other launchers remove dots when the notification is dismissed from the systems notification area. I suspect that the launchers are not practising voodoo magic and the developers found a technical way to implement this behaviour.

-----------------------------------------

The expectation, off course, varies depending on the user.
Other android based phones respect the notification status of the app and place the dots at apps with open notifications.
This is why me and some others have expected VollaLauncher to behave the same.

If the current behaviour is intentionally different from the behaviour of other launchers, I can accept that, I just see no advantage.

Anyway the Volla Launcher should respect the users choice in the app settings "allow App notification dots"

**Comment by wurzer** [comment]
implemented
