### ISSUE TITLE
PWA sometimes are not displayed in app screen

### ISSUE THREAD

**Issue by k-kirill** [HelloVolla/android-launcher-qt#201]
Steps to reproduce:
1. Install some PWA like YouTube in your browser
2. Open app screen in Volla launcher

Actual results:
YouTube PWA was not displayed

Expected results:
YouTube PWA should be displayed

Reproducible:
Not always, sometimes it doesn't work every 2nd time or every 5th time

Workaround:
One can switch between opened apps and Volla launcher and at some point PWA will be displayed

**Comment by k-kirill** [comment]
> What means PWA?

https://en.wikipedia.org/wiki/Progressive_web_app

**Comment by k-kirill** [comment]
As I wrote earlier for some websites there is an option to install PWA as well via the "Install" menu item and it is what i used. I don't use the "Add to Home screen" menu item, but I guess these shortcuts are affected as well.

**Comment by wurzer** [comment]
Please send post an example link

**Comment by k-kirill** [comment]
As mentioned in the description one can install YouTube PWA from https://youtube.com/

**Comment by wurzer** [comment]
I can't reproduce it. Please share a screenshot for the installation option in Fennec

**Comment by k-kirill** [comment]
Please make sure you open https://youtube.com/ and not https://m.youtube.com/. There is "Desktop site" switch in the three-dot menu for it.

**Comment by wurzer** [comment]
Can confirm this issue. We will invetigate

**Comment by wurzer** [comment]
Please retest. Should be solved with the recent release

**Comment by k-kirill** [comment]
I can no longer reproduce it in version 2.3.2. Thanks!
