### ISSUE TITLE
Springboard emoji misplaced

### ISSUE THREAD

**Issue by StaffanMelin** [HelloVolla/android-launcher-qt#203]
If you use emojis in the springboard, they are not placed correctly, too low, and the bottom is cut off.
![volla_springboard_emojis](https://github.com/HelloVolla/volla-os-beta-test/assets/33361311/0449f2cf-b318-4c14-a799-32d51e51e692)

BTW. It is not obvious that you need to hold down Enter to enter emoji mode, but maybe that is the fault of the AOSP keyboard.

**Comment by wurzer** [comment]
Can reproduce it. @erfanoabdi Looks like a font issue of Volla OS 13. Can't reproduce it on Volla OS 12

**Comment by wurzer** [comment]
Fixed in recent release
