### ISSUE TITLE
Springboard exit

### ISSUE THREAD

**Issue by StaffanMelin** [HelloVolla/android-launcher-qt#205]
If you call up the shortcuts by pressing the red dot, and then change your mind and want to start typing, there doesn't seem to be any obvious way to cancel the red shortcuts menu.

Suggestion: If you bring up the red menu w shortcuts, and press in the typing area at the top, cancel the menu.

**Comment by wurzer** [comment]
If you touch the red dot, the meni is opened and the last entry selected, I you dlightly move your thumb down and release it, the menu closes with no selection.

**Comment by StaffanMelin** [comment]
I can still get to a state where the menu is left on the screen, by moving my finger a bit down... Would've been handy if the menu disappeared when I click the text area on the top.
