### ISSUE TITLE
Collections not showing

### ISSUE THREAD

**Issue by Lucas-Sichardt** [HelloVolla/android-launcher-qt#206]
Hello, 

unfortunately on my X23 (version 12-20231128-STABLE-vidofnir) no collections are shown. As I think, I should be able to swipe from right to left to see contacts and even other collections like notes or news. At my system nothing happens when swiping from the right while by swiping from the left the apps and then settings appear normally.

**Comment by wurzer** [comment]
You need to call the collections from the red dot menu

**Comment by Lucas-Sichardt** [comment]
Ah, thanks!
Interesting workflow though.
I'll play around with it now...

-- 

Diese Nachricht wurde gesendet mit Evolution unter Linux Mint Xfce.Am Montag, den 25.12.2023, 02:33 -0800 schrieb Dr. Jörg Wurzer:
