### ISSUE TITLE
Suggestion: More Useful Functions For X23 Spotlight

### ISSUE THREAD

**Issue by Lucas-Sichardt** [HelloVolla/android-launcher-qt#207]
Hello,

I think the X23 Spotlight could have some more meaningful functions. While charging indication (battery level while charging) seems nice, it is in fact not so common to have the back of the device visible while charging, is it?
The same perhaps for other functions like notification light...

But what about the countdown for photos by self-timer?

Perhaps someone has even more really useful ideas?

Best regards,

Lucas

**Comment by wurzer** [comment]
See the system setting "sportlight". Here much more features like visializing music or notifying missed messages.
