### ISSUE TITLE
Torch light brightness

### ISSUE THREAD

**Issue by Lucas-Sichardt** [HelloVolla/android-launcher-qt#210]
Hello, 

after using the torch light feature for more than 5min (then automatic shutdown as set in the settings) the torch light is only available in reduced brightness at it seems. I already restarted the phone (X23) and before entering the PIN the torch light (set to be toggled by on/off key) is available in full brightness again. But after login (entering PIN) it is only available in reduced brightness again.

I guess there's a setting somewhere for this?

**Comment by wurzer** [comment]
Duplicate https://github.com/HelloVolla/volla-os-beta-test/issues/128
