### ISSUE TITLE
Wrong context menu if app grid contains both regular and PWA apps

### ISSUE THREAD

**Issue by k-kirill** [HelloVolla/android-launcher-qt#211]
Steps to Reproduce:
1. Install some PWA app like YouTube or add some website link
2. Open app grid
3. Open context menu for a regular app by tapping on it

Actual Results:
- PWA actions were displayed like "Open Shortcut" and "Remove Bookmark"

Expected Results:
- Only regular app actions should be displayed: "Add to shorcuts", "Remove App" (if applicable)

Notes:
- Same for PWA context menu: it contains the actions for a regular app, but it should not

**Comment by wurzer** [comment]
Should be solved with recent beta release

**Comment by k-kirill** [comment]
I cannot reproduce it in the version 2.3.3. Thanks!
