### ISSUE TITLE
Volla Security Mode - DNS 

### ISSUE THREAD

**Issue by huseyinkogo** [HelloVolla/android-launcher-qt#213]
Hi,

`Version: 12-20231228-STABLE-mimameid`

Recently i have updated my firewall settings on my business & home networks. Where i have disabled DNS lookup to every device, where i just want all the devices to use local DNS.

PROBLEM:
Yesterday I was playing with the Security Mode, when it is ON. The device is only using the 1.1.1.1 DNS.

How can this be disabled?

**Comment by wurzer** [comment]
This question is not related to the Volla launcher, but to Volla OS. You can define a custom DNS server in the system network settings.
