### ISSUE TITLE
Add ability to add launcher for Files (com.android.documentsui)

### ISSUE THREAD

**Issue by k-kirill** [HelloVolla/android-launcher-qt#214]
I wanted to add launcher for the Files app (com.android.documentsui) to the app grid screen, but it is not possible.
I tried disabling the File Manager app (com.simplemobiletools.filemanager.pro), but it just removed the existing Files launcher with the folder icon.
Please can you implement/allow such ability?
Thanks.

**Comment by wurzer** [comment]
Sorry I don't understand the issue. The file manager of simple mobile tools is whon in the app grid. With the concext menu, you can add this file manager to the quick menu.

**Comment by k-kirill** [comment]
I can add the Files app to the shortcuts indeed if I edit the `.shortcuts.json` file manually. But I do not want to do that as it will overload the menu with the items i do not use very often. All I want is to add the Files app to the app grid screen to have a quicker way to open it when needed like I can have it in the Trebuchet launder in the list of apps. Thanks.

**Comment by wurzer** [comment]
Did you already check the long press gesture to open the context menu and add an app to the quick menu?

**Comment by k-kirill** [comment]
As is wrote in the description, the Files app (com.android.documentsui) is not in the App grid list, nor can it be added there with Volla Launcher and this is what is the bug about.
In my comment I wrote that there is a way to it it to the shortcuts (the quick menu) by editing the  `.shortcuts.json` file manually.

**Comment by wurzer** [comment]
I see. You mean the Android file manager. Yes, it's not a bug. This app is hidden in the Volla launcher, to avoid confusion of two file apps.

**Comment by k-kirill** [comment]
I know it is not a bug, that is why I asked to implement/allow this ability:
>  Please can you implement/allow such ability?
I have also updated the summary to match the description.

**Comment by wurzer** [comment]
It would confuse users, if they find two file manager in the app overview. What is your intention or motivation to use a different file manager?

**Comment by k-kirill** [comment]
It makes perfect sense to hide it by default, but the ask (request) here is to add the ability to unhide it. I gave an example if I disable the File Manager app (com.simplemobiletools.filemanager.pro) in the settings then I will have no file manager in the app grid at all. Isn't Volla Phone about the choice and freedom? If so then why make it impossible for users to add another installed file manager to the app grid?

**Comment by wurzer** [comment]
Let's keep it as feature request. My question is: What are the features, that you are missing with the simple file manager or any other file manager app you can install? Maybe we find even a better solution.

**Comment by k-kirill** [comment]
I like its interface more: for me it is cleaner with the side bar that you can open via the hamburger menu in the top-left corner (similar to K-9 Mail, Telegram, etc), less distracting icons, etc, so I guess it's more a matter of opinion. I created this feature request to give users like me the ability to start another file manager via Volla Launcher (app grid) that you can easily do with the Trebuchet launcher.

**Comment by k-kirill** [comment]
For the time being one can install the following app to add the Files shortcut:
https://play.google.com/store/apps/details?id=com.marc.files

**Comment by wurzer** [comment]
Two file manger would confuse users

**Comment by k-kirill** [comment]
> Two file manger would confuse users

I have already clarified that this request is not about showing two file managers by default, but about adding the ability to show the Files app (com.android.documentsui) when I disable the default one the File Manager app (com.simplemobiletools.filemanager.pro) in the settings. Thanks!
