### ISSUE TITLE
Message appears every time Volla Launcher opens

### ISSUE THREAD

**Issue by franco-bez** [HelloVolla/android-launcher-qt#216]
![Screenshot_20240415-071414_Volla](https://github.com/HelloVolla/android-launcher-qt/assets/4195055/1376a078-4580-401a-a0b2-c97ccd29b517)

no matter if I click ok or cancel, the message comes again and again and again.

Latest Update of Launcher 2.3.4

**Comment by franco-bez** [comment]
I just noticed that there is also a typo in the message "anschliepend" ....

**Comment by vollafanboy** [comment]
I have the same problem since the last update of the VL.
What is to do?

**Comment by franco-bez** [comment]
> I have the same problem since the last update of the VL. What is to do?

Uninstall the update of VL and disable the Volla Nightly repository in Fdroid.

**Comment by vollafanboy** [comment]
I have the same problem since the last update of the VL.
What is to do?

**Comment by vollafanboy** [comment]
It worked!
But not via f-droid.
Had to deinstall out of the app list!
Thank's!!

**Comment by franco-bez** [comment]
> It worked! But not via f-droid. Had to deinstall out of the app list! Thank's!!

Fine.
I should have been more precise.
Uninstall the update of VL.
If you don't want the faulty update to show up again, also disable the Volla nightly repository in Fdroid.

**Comment by wurzer** [comment]
It's a known issue only for the veta version. I will fix it at the weekend.
