### ISSUE TITLE
Notes get erased occasionally

### ISSUE THREAD

**Issue by anulin** [HelloVolla/android-launcher-qt#232]
-Try to create a note and switch to some app. 
-check the notes
-if it is still there  try again 

eventually the note disappears/becomes empty

(I am using Volla X23)

**Comment by franco-bez** [comment]
see also
https://github.com/HelloVolla/android-launcher-qt/issues/183
https://github.com/HelloVolla/android-launcher-qt/issues/171

**Comment by wurzer** [comment]
So save a note you need to swipe balc to the springboard.

**Comment by anulin** [comment]
I did swipe. This happens to already existing notes

**Comment by wurzer** [comment]
Should be fixed
