### ISSUE TITLE
Add ability to open application properties from application grid

### ISSUE THREAD

**Issue by k-kirill** [HelloVolla/android-launcher-qt#242]
Please can you add a new "Information" menu item for applications in application grid to open App info for it?
Currently to check application permissions, clear its cache, etc one need to open settings, find the app there and only then can one check information about the application and edit its settings if necessary.

**Comment by wurzer** [comment]
You can check the appications permission at any time. You have several options. Go to system settings, then to apps, then to any app, finally open the permissions.

**Comment by k-kirill** [comment]
This issue is to add the ability to open app info right from the application grid in the application's menu and I know that I can open in via system settings, but it is not the request here. Thanks!
