### ISSUE TITLE
[Feature request] Offi app impossible to Create Launcher shortcut

### ISSUE THREAD

**Issue by Dricc123** [HelloVolla/android-launcher-qt#25]
On Dec 2, 2020 23:08, "Dr. Jörg Wurzer" info@volla.online wrote:
Thanks for your message. Unfortunately the Volla Launcher does not support a shortcut of a webage, that is shown up in the app grid like another app. However we will take your message as an inspiration to integrate bookmarks in thto the springboard concept.

Am 02.12.2020 um 22:21 schrieb Cedric D cedricoola@free.fr:

Hello Team,
See my screenshot please. I clicked 'Create Launcher Shortcut' but I don't see any shortcut created. Can you help?
Many thanks in advance
Cedric

![Screenshot_20201202-221840](https://user-images.githubusercontent.com/75565258/101279295-8dabe280-37c1-11eb-81c1-b62e4ffdd1ee.png)

**Comment by wurzer** [comment]
Implemented in recent release.
