### ISSUE TITLE
[Suggestion] Add a 'X' in the search field of the app grid

### ISSUE THREAD

**Issue by Dricc123** [HelloVolla/android-launcher-qt#26]
In the search field of the app grid, can we include a 'x' sign on the right side, so we don't have to untype what the field already contained from the previous search?

![Screenshot_20201206-135041](https://user-images.githubusercontent.com/75565258/101280639-850bda00-37ca-11eb-96f6-9ca5b2f3d85f.png)

**Comment by SimplyComple0x78** [comment]
Hey @Dricc123,
I totally agree and thus created [a PR for that](https://github.com/HelloVolla/android-launcher-qt/pull/30).
Additionally, I made (both) clear-buttons hide unless they contain text - you'll agree that this is the expected behavior.

**Comment by wurzer** [comment]
Implemented
