### ISSUE TITLE
APK for the Launcher

### ISSUE THREAD

**Issue by bigbavarian** [HelloVolla/android-launcher-qt#28]
I wish an Apk for the Launcher to use it in my non Volla device. Maybe an F-Droid repo for all the software you create. It is not possible for everyone to buy a new Smartphone but to try your Software. It also can be a good promo for your work. sry for my english. thank you

**Comment by TheOneWithTheBraid** [comment]
I already opened a corresponding issue: https://gitlab.com/fdroid/fdroiddata/-/issues/2234

Feel free to submit an F-Droid yaml-file containing the build instructions.

**Comment by nift4** [comment]
The licence doesn't allow redistrubution of APK or source code, so that is not possible.

**Comment by Tifter** [comment]
Would really like to see this

**Comment by wurzer** [comment]
We won't publish an AKP for the launcher, because the license only allows the distribution for the Volla Phone or the use by developers building the launcher on their own. We think about publishing a demonstrator of the launcher in a public repository like F-Droid.
