### ISSUE TITLE
[Issue] App drawer names

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#3]
When Google maps is installed alongside  OsmAnd it won't show up in the app drawer because OsmAnd is already named "Maps".

**Comment by SHA-NDY** [comment]
Any information regarding this issue?

**Comment by wurzer** [comment]
Will be fixed in next release > 1.1.0

**Comment by SHA-NDY** [comment]
Fixed! Thanks!
