### ISSUE TITLE
Springboard doesn't display contacts with @

### ISSUE THREAD

**Issue by flobon88** [HelloVolla/android-launcher-qt#33]
When trying to reach a contact with @ in Springboard, only newly added contacts are recognized and not the ones from Telegram that were added automatically.

**Comment by wurzer** [comment]
This is the expected behavior Only contacts from the device's contact store are considered (and accessible)

**Comment by wurzer** [comment]
Please recheck in beta release 2.0.16 to reload contacts in the launcher's settings.

**Comment by wurzer** [comment]
It's an expected behavior. You can reload contacts in the settings if necessary.
Please make sure, that the contacts are stored in the "Phone" storage and not only visible in the contact app.
