### ISSUE TITLE
Springboard inputs do not trigger communication context 

### ISSUE THREAD

**Issue by tux4us** [HelloVolla/android-launcher-qt#45]
VollaOS 10.0
VollaLauncher 1.8.0

Initial condition: all contacts are in Synch (CardDav) account.

What works: 

All contacts marked as favorites in the Contacts app as well as the last active contacts are displayed in Springboard - Contacts and can also be used via context menu to call as well as write SMS or eMail.   

Springboard - Conversations are displayed and can also be used to receive and write SMS, except creating new conversations as described below:

1. in the input line of Springboard I enter "@" and ALL contacts of my CardDav account are listed 
2. if I continue writing after "@", the contacts are filtered properly according to the input. 
3. if I select a contact, NO context menu for calling opens
4. if I enter more text, NO context menu for writing SMS or eMail opens

-------------------------------------------------------

Ausgangsbedingung: alle Kontakte befinden sich im Synch- (CardDav-) Konto.

Was funktioniert: 

Alle in der KontakteApp als Favoriten gekennzeichneten Kontakte sowie die letzten aktiven Kontakte werden im Sprungbrett - Kontakte angezeigt und können auch per Kontextmenü zum Anrufen sowie Schreiben von SMS bzw. eMail genutzt werden   

Sprungbrett - Unterhaltungen werden angezeigt und können auch genutzt werden zum Empfangen und schreiben von SMS, außer das Anlegen neuer Unterhaltungen wie nachfolgend beschrieben:

1. in der Eingabezeile des Sprungbrett gebe ich "@" ein und es werden ALLE Kontakte meines  CardDav-Kontos aufgelistet 
2. schreibe ich nach "@" weiter werden entsprechend der Eingabe die Kontakte ordnungsgemäß gefiltert. 
3. wähle ich einen Kontakt aus öffnet sich KEIN Kontextmenü zum Anrufen
4. gebe ich weiteren Text ein öffnet sich KEIN Kontextmenü zum Schreiben von SMS oder eMail

**Comment by tux4us** [comment]
Problem solved.

After several reboots did not bring any improvement I deleted the cache of the VollaLauncher and shut down and restarted the phone. All context functions are now available.

**Comment by wurzer** [comment]
The solution is much easier. If the contacts are out of sync. You can try two solutions:

1. Force the Volla launcher to stop and restart.
2. If this doesn't work: Delete the store and cache of the app.
