### ISSUE TITLE
[Issue] Not able to make call from springboard

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#5]
When a contact is selected while more than one contact matches the search criteria with @-prefix the "call" button doesn't work. Also the first matched contact name is covered by the "call" button.

**Comment by wurzer** [comment]
Can you re-check this issue?

**Comment by SHA-NDY** [comment]
I re-checked, it behaves in another buggy way now. Here is the behaviour in pictures:

![Screenshot_20200914-190324.png](https://user-images.githubusercontent.com/67801045/93116132-251b0100-f6bd-11ea-885f-7a6d22927a9d.png)

Press "Call"

![Screenshot_20200914-190334.png](https://user-images.githubusercontent.com/67801045/93116141-28ae8800-f6bd-11ea-897e-e10ae2bc51c3.png)


Resulting screen:

![Screenshot_20200914-190340.png](https://user-images.githubusercontent.com/67801045/93116147-2b10e200-f6bd-11ea-9918-5536ca72b373.png)

**Comment by wurzer** [comment]
I realized that. Did you update to the recent version? It should be 1.0.032.

**Comment by SHA-NDY** [comment]
I updated, still the same behaviour

**Comment by wurzer** [comment]
I can’t reproduce it. Can you reproduce this behavior for each address? Which phone numbers did you define for this contact? I mean, what is the syntax of the numbers and which label(s) has the phone number (mobile, work, home, etc)

**Comment by SHA-NDY** [comment]
I changed the label from "Sonstige" to "Mobil" and it worked. Don't know why this label is set. I sync with nextcloud and will have a look at my contacts there.
