### ISSUE TITLE
[Issue] App filter

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#6]
When apps are filtered and the filter is removed the apps list doesn't get unsorted again

**Comment by wurzer** [comment]
You mean is doesn't get sorted again?

**Comment by SHA-NDY** [comment]
So when I sort for "Ma" every app containing [MmAa] in its name is displayed.

![Screenshot_20200901-195645](https://user-images.githubusercontent.com/67801045/91890289-89869b00-ec8f-11ea-95ad-d3fdb7af0008.png)

When the filter is reduced to "M" the previous sorting is persistent and additionally all apps with [Mm] in their names are displayed.

![Screenshot_20200901-195703](https://user-images.githubusercontent.com/67801045/91890294-8ab7c800-ec8f-11ea-914d-a4c5e8a511ae.png)

The same happens when sorted for "Sd". All apps with [SsDd] are displayed.

![Screenshot_20200901-195753](https://user-images.githubusercontent.com/67801045/91890300-8be8f500-ec8f-11ea-98ba-4abbb152d46d.png)

When sortstring is reduced to "S" all apps with [Ss] in their names are displayed.

![Screenshot_20200901-195804](https://user-images.githubusercontent.com/67801045/91890307-8d1a2200-ec8f-11ea-8462-35f582abaf12.png)

When the sortstring gets removed all previously sorted apps stay at the top of the apps list and afterwards the unsorted apps are listed. 

![Screenshot_20200901-195828](https://user-images.githubusercontent.com/67801045/91890311-8e4b4f00-ec8f-11ea-8995-55abbeb13482.png)

**Comment by SHA-NDY** [comment]
It's better now, but shouldn't be Titanium Backup on top of the sorted list in the following example?

![Screenshot_20200914-185802.png](https://user-images.githubusercontent.com/67801045/93115596-5ba44c00-f6bc-11ea-8cb7-8e1152864232.png)

**Comment by wurzer** [comment]
T comes after S. The apps are currently sorted by name in an ascending order.

**Comment by SHA-NDY** [comment]
But I would expect to get results starting with "Ti" first because in "Spotify" the "Ti" comes later in the word.

**Comment by wurzer** [comment]
Ah, now I understand. I’ts not a sorting issue, isn’t it. The filter is implemented as a string match somewhere in the word, not only at the beginning of a word. What you would like to have is a match of the beginning of a word

**Comment by SHA-NDY** [comment]
Right. In the first place string matches at the beginning of the word and then the remaining matches

**Comment by SHA-NDY** [comment]
New behaviour in 1.1.3:

Sorting produces an empty result and after removing a second character from the sortstring the correct result shows up

![Screenshot_20201008-190018.png](https://user-images.githubusercontent.com/67801045/95491132-7d31e400-0999-11eb-8451-13824b9182d1.png)

![Screenshot_20201008-190029.png](https://user-images.githubusercontent.com/67801045/95491146-815e0180-0999-11eb-87a8-0fb8dd8821ee.png)

![Screenshot_20201008-190038.png](https://user-images.githubusercontent.com/67801045/95491160-84f18880-0999-11eb-8146-0ea2d91e05e1.png)

**Comment by SHA-NDY** [comment]
Fixed in 1.1.5
