### ISSUE TITLE
[Suggest] More simple apps

### ISSUE THREAD

**Issue by SHA-NDY** [HelloVolla/android-launcher-qt#7]
If more apps from simple mobiletools (e.g. simple contacts, simple dialer, simple sms, ...) were used the overall user experience (black color looks very good with volla launcher) would be more consistent.

**Comment by wurzer** [comment]
Yes, we will use the simple dialer, messages and clock. It comes with the next beta update.

**Comment by SHA-NDY** [comment]
That's great news. I like the simplicity of these apps and the possibility to have a real dark design on them.
