### ISSUE TITLE
Language Settings - Shortcuts are kept in former language

### ISSUE THREAD

**Issue by rb-cl** [HelloVolla/android-launcher-qt#81]
If you change the language from German to English a restart is required for the Launcher, not for the rest. The shortcuts are still kept in the former Language (German) in this case. Probably no bug but a missing feature, not high priority but helpful.

**Comment by wurzer** [comment]
This is currently the expected behavior. Live switch of languages is not supported yet.

**Comment by wurzer** [comment]
No, if you change the shortcuts, they are updated as soon you open the shortcuts again.
