### ISSUE TITLE
Launcher freezes wenn Notes are selected via shortcut

### ISSUE THREAD

**Issue by rb-cl** [HelloVolla/android-launcher-qt#84]
Situation: VollaPhone 22, update Launcher to 2.0.32 yesterday, update Volla OS today. Notes app vanished with the OS update. My three notes that were created via the launcher were still available. I was able to create a new note once. After a second attempt the launcher was freezing. It's now always freezing when I select notes - only restart helps.

**Comment by wurzer** [comment]
Since the notes app is removed, we'll remove this default shortcut.

**Comment by wurzer** [comment]
You need to update the Volla app in F-Droid. The recent version is 2.0.32
