### ISSUE TITLE
Arrangement of Apps not as expected

### ISSUE THREAD

**Issue by everyusernameistaken123** [HelloVolla/android-launcher-qt#87]
Steps:
In Volla launcher, swipe to Apps (or have it as default start screen)
Use the phone for a day (in my case, I was using "Settings" (=F-Droid settings) a lot

Expected:
There is a "most used" selection. I obviously expect that "most used" apps will be shown there

Actual:
Arrangement / Order of apps is unchanged (i.e. "Settings" is still on the "second page")

Environment: Volla Phone 22, Volla OS 11.1-20220719-STABLE-mimameid, almost only default apps, just Signal installed in addition.

Details:
I would somehow understand when this is just updated once per day, but ideally more frequently. Respectively it should work at all ;)

**Comment by wurzer** [comment]
Fixed with release 2.0.32
