### ISSUE TITLE
Setting "Colored app icons" not working

### ISSUE THREAD

**Issue by everyusernameistaken123** [HelloVolla/android-launcher-qt#88]
Steps:
In Volla launcher, swipe to Settings
Tap on "Display and menus"
Tap "Use colored app icons"

Expected:
app icons in "Apps" section are colored

Actual:
They stay the same

Environment: Volla Phone 22, Volla OS 11.1-20220719-STABLE-mimameid, almost only default apps, just Signal installed in addition.

Details:
Changing the setting mutliple times, switching to other apps etc. also does not resolve the issue. Icons always stay uncolored.

**Comment by wurzer** [comment]
Fixed with release 2.0.32
