### ISSUE TITLE
Color fault of icons in App view (during slow scrolling)

### ISSUE THREAD

**Issue by HeeLoco** [HelloVolla/android-launcher-qt#9]
Hello,

While using the Volla Phone I often notice that in the app view the icons are not always completely grey.

**Steps to reproduce:**

1. Unlock Phone 
2. Go to Springboard
3. Swipe to the App overview
4. Scroll down/up slowly to see the color change effect of App icons

**Expected:**
- Every App is shown correctly

**Actual:**
- Color is not displayed correcty

**Further Information:**
OS Version: 9
Build number: PPR1.180610.011 dev-keys
Custom bild version: alps-mp-p0.mp7-V2.51_prize.p0mp7.k57pv1.dm.64_P7
Volla Launcher App Version: 1.0.19 (added 31.08.2020)
The problem already existed before the update on 31.08.2020

**Pictures:**
![Screenshot_20200828-233429](https://user-images.githubusercontent.com/66466597/91726180-1e11d000-eba0-11ea-916e-b95d642949df.png)
![Screenshot_20200828-233543](https://user-images.githubusercontent.com/66466597/91726186-210cc080-eba0-11ea-830f-7b8b24925d29.png)

BR HeeLoco

**Comment by wurzer** [comment]
You mean the small red border?

**Comment by HeeLoco** [comment]
Yes, I marked them in the screenshots.
Red -> SoundCloud 
Green -> Whatsapp
Blue -> Open Camera
Turquoise -> N26 
Is seems that the color of the borders changes depending on the nativ App color

**Comment by wurzer** [comment]
I have explicitly set the border color as transparent. Could you check the release > 1.1.0

**Comment by SHA-NDY** [comment]
This issue is still persistent in version 1.1.3

![Screenshot_20201008-093058_1.png](https://user-images.githubusercontent.com/67801045/95428311-27cde680-0949-11eb-9bcb-59d3403bf5c1.png)

**Comment by SHA-NDY** [comment]
Still persistent in 1.2.0

**Comment by nift4** [comment]
Still persistent in the newest release

**Comment by SimplyComple0x78** [comment]
I can confirm this in 1.2.1, in my case it's Keepass having a thin blue border (even before scrolling the view at all).

**Comment by wurzer** [comment]
Please check, if still relevant.
